import { Poppins } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "@/utils/SmoothScrollWrapper";

export const popin = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Lanudry & Dry Cleaning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={popin.className}>{children}</body>
    </html>
  );
}
